update 1.0.6

diff --git a/daemon/src/cute-getfastmirror b/daemon/src/cute-getfastmirror
--- a/daemon/src/cute-getfastmirror
+++ b/daemon/src/cute-getfastmirror
@@ -1,28 +1,27 @@
 #!/bin/bash
 
-VERSION="swifts"
+VERSION="1.0.0"
 
-TEST_NETCONNECT_HOST="www.cuteos.cn"
+TEST_NETCONNECT_HOST="lingmo.org"
 
-#SOURCES_MIRRORS_FILE="/etc/apt/update.list"
+SOURCES_MIRRORS_FILE="/etc/cute-apt/sources_mirrors.list"   
 
-MIRRORS_SPEED_FILE="/etc/apt/mirrors_speed.list"
+MIRRORS_SPEED_FILE="/etc/cute-apt/mirrors_speed.list"
 
-SOURCES_MIRRORS_FILE_URL="https://3"
+SOURCES_MIRRORS_FILE_URL="http://packages.apt.lingmo.org/"
 
 function get_mirror_list()
 {
-    echo "检查版本666..."
+    wget $SOURCES_MIRRORS_FILE_URL --output-document=$SOURCES_MIRRORS_FILE
 }
 
 function get_ping_speed()    #return average ping $1 time
 
 {
 
-#    local speed=`ping -W1 -c1 $1 2> /dev/null | grep "^rtt" |  cut -d '/' -f5`
+    local speed=`ping -W1 -c1 $1 2> /dev/null | grep "^rtt" |  cut -d '/' -f5`
 
-#    echo $speed.
-    echo "检查版本..."
+    echo $speed
 
 }
 
@@ -30,42 +29,41 @@ function test_mirror_speed()    #
 
 {
 
-    # rm $MIRRORS_SPEED_FILE 2> /dev/null; touch $MIRRORS_SPEED_FILE
+    rm $MIRRORS_SPEED_FILE 2> /dev/null; touch $MIRRORS_SPEED_FILE
 
    
 
-    #  cat $SOURCES_MIRRORS_FILE | while read mirror
+     cat $SOURCES_MIRRORS_FILE | while read mirror
 
-    # do
+    do
 
-    #     if [ "$mirror" != "" ]; then
+        if [ "$mirror" != "" ]; then
 
-    #         echo -e "Ping $mirror c"
+            echo -e "Ping $mirror c"
 
-    #         local mirror_host=`echo $mirror | cut -d '/' -f3`    #change mirror_url to host
-
-   
-
-    #         local speed=$(get_ping_speed $mirror_host)
+            local mirror_host=`echo $mirror | cut -d '/' -f3`    #change mirror_url to host
 
    
 
-    #         if [ "$speed" != "" ]; then
+            local speed=$(get_ping_speed $mirror_host)
 
-    #             echo "Time is $speed"
+   
 
-    #             echo "$mirror $speed" >> $MIRRORS_SPEED_FILE
+            if [ "$speed" != "" ]; then
 
-    #         else
+                echo "Time is $speed"
 
-    #             echo "Connected failed."
+                echo "$mirror $speed" >> $MIRRORS_SPEED_FILE
 
-    #         fi
+            else
 
-    #     fi
+                echo "Connected failed."
 
-    # done
-    echo "检查版本2..."
+            fi
+
+        fi
+
+    done
 
 }
 
@@ -73,12 +71,11 @@ function get_fast_mirror()
 
 {
 
-    # sort -k 2 -n -o $MIRRORS_SPEED_FILE $MIRRORS_SPEED_FILE
+    sort -k 2 -n -o $MIRRORS_SPEED_FILE $MIRRORS_SPEED_FILE
 
-    # local fast_mirror=`head -n 1 $MIRRORS_SPEED_FILE | cut -d ' ' -f1`
+    local fast_mirror=`head -n 1 $MIRRORS_SPEED_FILE | cut -d ' ' -f1`
 
-    # echo $fast_mirror
-    echo "检查版本3..."
+    echo $fast_mirror
 
 }
 
@@ -86,59 +83,58 @@ function update_sources()
 
 {
 
-    # local COMP="main"
+    local COMP="main"
 
-    # local mirror="$1"
+    local mirror="$1"
 
-    # local tmp=$(mktemp)
+    local tmp=$(mktemp)
 
-    # echo "deb [arch=amd64] $mirror $VERSION $COMP" >> $tmp
+    echo "deb [arch=amd64] $mirror $VERSION $COMP" >> $tmp
 
-    # sudo mv "$tmp" /etc/apt/sources.list.d/cute-os.list
+    sudo mv "$tmp" /etc/apt/sources.list.d/lingmo.list
 
-    # echo -e "Your sources has been updated, and maybe you want to run "sudo apt-get update" now.n";
+    echo -e "Your sources has been updated, and maybe you want to run "sudo apt-get update" now.n";
 
-    echo "检查版本4..."
 }
 
 echo -e "nTesting the network connection.nPlease wait...   c"
 
-# if [ "$(get_ping_speed $TEST_NETCONNECT_HOST)" == "" ]; then
+if [ "$(get_ping_speed $TEST_NETCONNECT_HOST)" == "" ]; then
 
-#     echo -e "Network is bad.nPlease check your network."; exit 1
+    echo -e "Network is bad.nPlease check your network."; exit 1
 
-# else
+else
 
-#     echo -e "Network is good.n"
+    echo -e "Network is good.n"
 
-#     mkdir -p /etc/cute-apt/
+    mkdir -p /etc/lingmo-apt/
 
-#     get_mirror_list
+    get_mirror_list
 
-#     test -f $SOURCES_MIRRORS_FILE
+    test -f $SOURCES_MIRRORS_FILE
 
-#     if [ "$?" != "0" ]; then 
+    if [ "$?" != "0" ]; then 
 
-#         echo -e "$SOURCES_MIRRORS_FILE is not exist.n"; exit 2
+        echo -e "$SOURCES_MIRRORS_FILE is not exist.n"; exit 2
 
-#     else
+    else
 
-#         test_mirror_speed
+        test_mirror_speed
 
-#         fast_mirror=$(get_fast_mirror)
+        fast_mirror=$(get_fast_mirror)
 
-#         if [ "$fast_mirror" == "" ]; then
+        if [ "$fast_mirror" == "" ]; then
 
-#             echo -e "Can't find the fastest software sources. Please check your $SOURCES_MIRRORS_FILEn"
+            echo -e "Can't find the fastest software sources. Please check your $SOURCES_MIRRORS_FILEn"
 
-#             exit 0
+            exit 0
 
-#         fi
+        fi
 
-#         update_sources $fast_mirror
+        update_sources $fast_mirror
 
-#     fi
+    fi
 
-# fi
+fi
 
 exit 0
